version: '2'

networks:
  my-net:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  mysql8:
    build: ./files_docker/mysql8
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=BLBJn_1993
      - MYSQL_ACCESS_IP=127.0.0.1
      - MYSQL_USER_LOGIN=jeha03
      - MYSQL_USER_PASSWORD=BLBJn_1993
      - MYSQL_DATABASE=laravel
      - MYSQL_DATABASE_OTHER1=rusacis
      - MYSQL_DATABASE_SHEMA1=/temp_sql/acis/*.sql
      - MYSQL_DATABASE_OTHER2=lucera
      - MYSQL_DATABASE_SHEMA2=/temp_sql/lucera/*.sql
      - MYSQL_DATABASE_OTHER3=pwsoft
      - MYSQL_DATABASE_SHEMA3=/temp_sql/pwsoft/*.sql
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    networks:
      my-net:
        ipv4_address: 172.20.0.4

  laravel:
    build: ./files_docker/laravel9
    stdin_open: true
    ports:
      - '8000:8000'
      - '5173:5173'
    networks:
      my-net:
        ipv4_address: 172.20.0.5
    environment:
      - DB_HOST=172.20.0.4
      - DB_USERNAME=jeha03
      - DB_DATABASE=laravel
      - DB_PASSWORD=BLBJn_1993
      - DB_CONNECTION_SECOND=mysql
      - DB_HOST_SECOND=172.20.0.4
      - DB_PORT_SECOND=3306
      - DB_DATABASE_SECOND=rusacis
      - DB_USERNAME_SECOND=jeha03
      - DB_PASSWORD_SECOND=BLBJn_1993
      - DB_CONNECTION_THREE=mysql
      - DB_HOST_THREE=172.20.0.4
      - DB_PORT_THREE=3306
      - DB_DATABASE_THREE=pwsoft
      - DB_USERNAME_THREE=jeha03
      - DB_PASSWORD_THREE=BLBJn_1993
      - DB_CONNECTION_FOUR=mysql
      - DB_HOST_FOUR=172.20.0.4
      - DB_PORT_FOUR=3306
      - DB_DATABASE_FOUR=lucera
      - DB_USERNAME_FOUR=jeha03
      - DB_PASSWORD_FOUR=BLBJn_1993
      - APP_URL=http://45.12.236.179
    depends_on:
      - mysql8

volumes:
  mysql_data:
    driver: local
